### PR TITLE
[MIG] Add Migration FSO Types

### PR DESCRIPTION
**Pull request by osi-scampbell**
This is the migration script + demo data needed for the migration script. To execute the migration script, upgrade the fieldservice module from the backend.

### CODE REVIEW

**Comment by max3903** [comment]
@osi-scampbell Should be made against the OCA/12.0 branch.

**Comment by smangukiya** [comment]
@max3903 : Doesn't this suppose to be for Pavlov only?

**Comment by osi-scampbell** [comment]
@smangukiya This change was pushed to OCA as well so it should be in OCA, from there we can cherry-pick the commit into 12,0-pvm

**Comment by smangukiya** [comment]
> @smangukiya This change was pushed to OCA as well so it should be in OCA, from there we can cherry-pick the commit into 12,0-pvm

@osi-scampbell : Thanks Steve but I am asking this because my next point is the PAVLOV production database has the following type available, we need to add specific demo data along with this migration too.
image

@max3903 : How to handle demo data which is related to RMA?

Thanks

**Pull request closed without merging**
